name: ChestLogger
version: 0.1.0
api-version: 1.18
author: cfrankovich
main: dev.frankovich.main.Main
description: Keeps track of chests with a ledger and watchlist.

commands:
  chest:
    description: Full description on github (https://github.com/cfrankovich/ChestLogger)