name: ChestLogger
version: 1.0
author: cfrankovich
main: dev.frankovich.main.Main
description: Keeps track of chests with a ledger and watchlist.

commands:
  chest:
    description: Full description on github (github/cfrankovich/ChestLogger)